name: CI
on: [push, pull_request]

jobs:
  check:
    name: Hardhat Foundry Starter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.0"

      - name: Install npm dependencies
        run: npm install

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run forge tests
        run: forge test -vvv

      - name: Run Hardhat tests
        run: npx hardhat test
